### ISSUE TITLE
danmaQ is not work on RHEL6.5 host 

### ISSUE THREAD

**Issue by vipmike007** [bigeagle/danmaQ#1]
Hi, Not sure you want to fix or not ,I find sth wrong on RHEL6u5 host to run the scripts

packages
kernel-2.6.32-422.el6.x86_64
PyQt4-4.6.2-9.el6.x86_64
qt-4.6.2-28.el6_5.x86_64
python-2.6.6-52.el6.x86_64

Each time I send shoot in wechat ,it will shows :
$ python danmaQ.py 
Traceback (most recent call last):
  File "/home/bcao/git/danmaQ/danmaQ/app.py", line 126, in on_subscription_started
    "Subscribing danmaku from {}".format(self.workThread.server)
ValueError: zero length field name in format
Traceback (most recent call last):
  File "/home/bcao/git/danmaQ/danmaQ/app.py", line 103, in on_new_danmaku
    dm = Danmaku(text, style=style, position=position, parent=self)
  File "/home/bcao/git/danmaQ/danmaQ/danmaq_ui.py", line 74, in **init**
    self.init_text(text, style)
  File "/home/bcao/git/danmaQ/danmaQ/danmaq_ui.py", line 93, in init_text
    effect = QtGui.QGraphicsDropShadowEffect(self)
AttributeError: 'module' object has no attribute 'QGraphicsDropShadowEffect'

**Comment by bigeagle** [comment]
Hi, the current version supports python 2.7 and python 3. 
I'm not quite interested in old version support, but according the traceback, you can try to comment out these lines of code since they're not the core part.

**Comment by xxairwolf** [comment]
openSUSE 13.1 64位 KDE桌面
Python 2.7.6
Qt version 4.8.5
发弹幕的时候不显示弹幕且有如下错误。
Traceback (most recent call last):
  File "/home/xuxiao/Projects/danmaQ/danmaQ/app.py", line 104, in on_new_danmaku
    dm = Danmaku(text, style=style, position=position, parent=self)
  File "/home/xuxiao/Projects/danmaQ/danmaQ/danmaq_ui.py", line 67, in **init**
    text = self.escape_text(text)
  File "/home/xuxiao/Projects/danmaQ/danmaQ/danmaq_ui.py", line 62, in escape_text
    text = re.sub(r'\\n', r'\n', text)
  File "/usr/lib64/python2.7/re.py", line 151, in sub
    return _compile(pattern, flags).sub(repl, string, count)
AttributeError: 'QString' object has no attribute 'join'
如果我把danmaq_ui.py", line 67注释掉，可以显示弹幕，但是颜色设置无效（就是说全都是白色弹幕）；位置设置只有顶部是顶部弹幕，其它都是飞过弹幕。m(_ _)m

**Comment by bigeagle** [comment]
貌似的确在 KDE 下有些问题，我再测测

**Comment by bigeagle** [comment]
@xxairwolf 目测是参数类型不对，再试试？

**Comment by xxairwolf** [comment]
@bigeagle 弹幕只有顶部和飞过的问题解决了，服务器代码中shared.py的bottom误打成buttom了。
https://github.com/tuna/gdanmaku-server/issues/8
发在这里不知是否正确

**Comment by bigeagle** [comment]
@xxairwolf 非常感谢！
